### PR TITLE
support for XP-PEN Star G640 tablet. just copied the lines from the e…

### PR DESCRIPTION
**Pull request by automenta**
…xisting G540 for G640 and added its unique hardware ID number.  make install and now it seems to work (debian buster/sid kernel 4.16.0).  pressure sensitivity working also.

### CODE REVIEW

**Comment by danghai** [comment]
Thanks @automenta . Could you also help us provide information of your tablet regarding to `descriptor`, `frame_buttons`, `pen_buttons`, `pen_coords`, `pen_pressure`, `pen_tilt`, `hid_report_descriptors`, and `probe`? Thanks a lot

**Comment by automenta** [comment]
let me know if you need anything else:

**usb-devices**
```
T:  Bus=01 Lev=03 Prnt=06 Port=03 Cnt=02 Dev#= 26 Spd=12  MxCh= 0
D:  Ver= 1.10 Cls=00(>ifc ) Sub=00 Prot=00 MxPS=64 #Cfgs=  1
P:  Vendor=28bd ProdID=0094 Rev=00.00
S:  Manufacturer=XP-PEN
S:  Product=STAR G640
C:  #Ifs= 3 Cfg#= 1 Atr=80 MxPwr=70mA
I:  If#= 0 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=01 Prot=02 Driver=usbhid
I:  If#= 1 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=01 Prot=02 Driver=usbhid
I:  If#= 2 Alt= 0 #EPs= 2 Cls=03(HID  ) Sub=00 Prot=00 Driver=usbhid
```

**xinput list "pointer:XP-PEN STAR G640"**
```
XP-PEN STAR G640                        	id=15	[slave  pointer  (2)]
	Reporting 7 classes:
		Class originated from: 15. Type: XIButtonClass
		Buttons supported: 10
		Button labels: "Button Left" "Button Middle" "Button Right" "Button Wheel Up" "Button Wheel Down" "Button Horiz Wheel Left" "Button Horiz Wheel Right" "Button Side" "Button Extra" "Button Forward"
		Button state:
		Class originated from: 15. Type: XIValuatorClass
		Detail for Valuator 0:
		  Label: Rel X
		  Range: -1.000000 - -1.000000
		  Resolution: 0 units/m
		  Mode: relative
		Class originated from: 15. Type: XIValuatorClass
		Detail for Valuator 1:
		  Label: Rel Y
		  Range: -1.000000 - -1.000000
		  Resolution: 0 units/m
		  Mode: relative
		Class originated from: 15. Type: XIValuatorClass
		Detail for Valuator 2:
		  Label: Rel Horiz Scroll
		  Range: -1.000000 - -1.000000
		  Resolution: 0 units/m
		  Mode: relative
		Class originated from: 15. Type: XIValuatorClass
		Detail for Valuator 3:
		  Label: Rel Vert Scroll
		  Range: -1.000000 - -1.000000
		  Resolution: 0 units/m
		  Mode: relative
		Class originated from: 15. Type: XIScrollClass
		Scroll info for Valuator 2
		  type: 2 (horizontal)
		  increment: 15.000000
		  flags: 0x0
		Class originated from: 15. Type: XIScrollClass
		Scroll info for Valuator 3
		  type: 1 (vertical)
		  increment: 15.000000
		  flags: 0x0
```

**Comment by automenta** [comment]
that xinput output is from before installing the new driver.  if you need its output from after the driver is running, ill get it soon when i reconnect the tablet again

**Comment by danghai** [comment]
@automenta I need these data to put them into tablet's repo. These data look like this: https://github.com/DIGImend/tablets/tree/master/XP-Pen_G430
You can take this by: 
http://digimend.github.io/support/howto/trbl/diagnostics/

**Comment by spbnick** [comment]
I removed some trailing whitespace, cleaned up the commit message and pushed this to master. Thank you, @automenta!

**Pull request closed without merging**
