### PR TITLE
uclogic: Extract report descriptors to a module

### PR DESCRIPTION
**Pull request by spbnick**
This is based on and to replace #97, with amendments and additions. @Garethp, could you do a review please? Thank you.

### CODE REVIEW

**Comment by Garethp** [comment]
Sorry I didn't get around to working on my PR sooner. Still getting over sickness from December.

It looks good. I suppose it's not an issue, but is there a reason why you moved the `sizeof` calculations to constants? They would execute and calculate the `sizeof` devices that wouldn't be needed, wouldn't it?

**Comment by Garethp** [comment]
Also unimportant, but I noticed that some of the `ORIG_SIZE` definitions have their values column aligned, and others don't. Do you have a preference?

**Comment by spbnick** [comment]
Thanks for the review, Gareth! No problem about the PR.

The sizeof variables are needed because otherwise hid-uclogic.c wouldn't know the sizes of the report descriptors. I'm not sure why it compiled for you. Perhaps some GCC feature is turned off for the kernel, but the code shouldn't actually work, even though it compiles.

The ORIG_SIZE macros are not aligned because I copied them verbatim from hid-uclogic.c. I added another commit aligning them.

Does it look alright to you now?

**Comment by Garethp** [comment]
It all looks good

**Comment by spbnick** [comment]
Merged. Thank you, Gareth!

**Pull request closed without merging**
