### PR TITLE
Update testing dkms in Travis

### PR DESCRIPTION
**Pull request by danghai**
I make PR to update testing `dkms` in Travis. I am not sure the option `--no-depmod`. It seems there is no option for `dkms install`. You can see the error in status Travis

### CODE REVIEW

**Comment by spbnick** [comment]
This might be because dkms in Ubuntu 14.04.5 LTS is too old. Install it into a vm (e.g. in virt-manager), and check. If that's so, we might need to remove --no-depmod option from the Makefile, or implement detection of dkms versions which don't support it, according to the code complexity vs. performance hit trade-off.

**Comment by danghai** [comment]
@spbnick right, I try to install ubuntu-18.04 , and it works with option `--no-depmod`. My old ubuntu 14 does not work for both `dkms uninstall` and `dkms install`. So what do you think good solution? Could you implement detection of dkms versions? It means write `if-condition` in Makefile to make sure work for old and newest distribution?

**Comment by spbnick** [comment]
First, measure what the time difference for running with and without `--no-depmod` option will be, on 18.04. Use the `time` built-in command, watch the `real` line. I.e. `time sudo make_dkms_install`. If it's just a few seconds, just submit a PR removing the `--no-depmod` option for now.

**Comment by danghai** [comment]
The time: 
```
install hid-rebind /sbin/hid-rebind
install -m 0644 90-hid-rebind.rules /lib/udev/rules.d/90-hid-rebind.rules
udevadm control --reload

real	0m4.218s
```
What does the option `--no-depmod` do?

**Comment by spbnick** [comment]
Read the dkms manual :) Try removing it and compare the installation/uninstallation time.

**Comment by danghai** [comment]
The time without option: `0m4.503s`

**Comment by spbnick** [comment]
And with the option? Is the difference worth having the detection code added?

**Comment by danghai** [comment]
In Ubuntu 18:
with `--no-depmod`: 0m4.218s
without  `--no-depmod`: 0m4.503s
In ubuuntu 14:
without  `--no-depmod`: 0m16.102s

**Comment by spbnick** [comment]
Really? No difference with `--no-depmod`? Wow. OK, could you please post a PR removing the `--no-depmod` use both from `dkms_install` and `dkms_uninstall`. Thank you.

**Comment by danghai** [comment]
@spbnick yeah, I have checked 2 times. There is no much difference time between with/without `--no-depmod`. I add 1 commit to remove the option `--no-depmod`. Travis is frozen now :)

**Comment by spbnick** [comment]
Thank you, Hai! I switched the order of commits to keep the CI working, added commit descriptions and fixed one comment, in PR #166. Closing this one.

**Comment by danghai** [comment]
@spbnick Could you help me how to reorder the commit in git quickly? For example, if I have 3 commits `A --> B --> C`, How can I reorder commit `C-->B-->A`?

**Comment by spbnick** [comment]
Use interactive rebase (`git rebase -i`), and then just switch the lines around :)

**Comment by danghai** [comment]
Oh Thanks. It is really simple :)

**Pull request closed without merging**
