### PR TITLE
Xppen artist 10s (1st gen)

### PR DESCRIPTION
**Pull request by hooger**
I tried to address #137. As said in the issue, I'm not sure if I should check anything or I should do anything beside the obvious changes. Please throw me a comment if anything else is needed!

### CODE REVIEW

**Comment by hooger** [comment]
I modified the commit message, so it contains a sign-off. Hope it helps to merge.

**Comment by spbnick** [comment]
@hooger, Thanks for the contribution! The Sign-off is not really necessary for merging, but would help when contributing upstream. Is all the functionality working? Do you have pressure, are you able to remap the buttons on the frame?

If everything is working, please **rebase** your commit on latest master (instead of merging master into your branch), and I'll merge it.

**Comment by hooger** [comment]
I think this is rebased now, no master merge.

The tablet has working preassure sensitivity (however the default is quite firm, but nothing xsetwacom couldn't handle) buttons can be mapped to keypresses, stylus buttons work. Yesterday I realized that even tilt works, however I couldn't find a way to set that up.

**Comment by hooger** [comment]
There was a conflict in xorg.conf that I resolved using the inbuilt editor of github. Can I do anything to merge my PR?

**Comment by hooger** [comment]
Necro bump. I tested this again (I haven't been using the table for a while) and it does seem to work, however there is no tilt support. I haven't found any information if the tablet should support tilt or not. `evtest` does not report any tilt events. Preassure works, buttons on the tablet and the pen is configurable.

I rebased the PR onto the current master. Is there anything I can do to help with the merge?

**Comment by hooger** [comment]
Is there anything I can do to speed up merge?

**Comment by hooger** [comment]
@JoseExposito sry for tagging you in this PR, but you seems to be the most active member currently. Can you please check this PR and merge it if possible?

Also, can you tell me something about the current state of the project?  Is it being maintained? Are these patches somehow getting upstreamed or it should be done differently? I don't see if this branch of code is intended to be always be a separate code branch or you as the maintainers working on upstreaming them?

Hope you can take a look at the PR and answer my questions!
Best regards,
hooger

**Review by JoseExposito — APPROVED** [review]
Sorry @hooger, I recently got merge permissions but I ignored old PRs because, at this point, most users won't be open to implement changes.

You change looks good to me, thanks a lot.

About the status of the project, it is mostly unmaintained and I'm upstreaming bug fixes to the kernel but not new devices.

Instead, we decided to start using HID-BPF. Here is a quick summary:
https://github.com/DIGImend/digimend-kernel-drivers/pull/693#issuecomment-2126861337

One of the reasons is that there are some devices handled by UCLogic that expose a structure that user-space can't handle and we cannot fix them without causing regressions.
In addition, the developer experience using HID-BPF is way better than kernel programming.

I'm going to merge your code but, as I mentioned, I won't upstream it. If you have some time, I'd suggest to create a HID-BPF driver. It is very simple. A couple of examples:
- https://gitlab.freedesktop.org/libevdev/udev-hid-bpf/-/merge_requests/88
- https://gitlab.freedesktop.org/libevdev/udev-hid-bpf/-/merge_requests/87

And there are more in the repo. I think that udev-hid-bpf is the best way to get your changes upstreamed.

Meanwhile, you can use DIGImend :)

**Comment by hooger** [comment]
Sorry for the late reply! Thank you for the merge and also for the tip on hid-bpf. I will take a look at it.

**Pull request merged**
