### PR TITLE
To fix dkms remove issue.

### PR DESCRIPTION
**Pull request by uhuntu**

### CODE REVIEW

**Comment by spbnick** [comment]
Thank you for the PR, @uhuntu. However, could you please describe what is the problem you're trying to solve, and why your fix works? Thank you!

**Comment by nic3-14159** [comment]
Just a note, I think this accomplishes the same thing as 60f62f50834d6e52654b84af1592568f5ec15873 in #594

**Comment by spbnick** [comment]
Ah, thank you, @nic3-14159. I'll take a look at that.

**Comment by spbnick** [comment]
Fixed in #629. Thank you!

**Pull request closed without merging**
